name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust Toolchain
      run: |
        curl --proto https --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source ~/.cargo/env
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4 
      with:
          name: docs-helper
          path: target/release/docs-helper
